<a href="https://colab.research.google.com/github/Manireddy69/GATE/blob/main/ML_from_scratch_for_GATE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
x = np.array([1,2,3,4]).reshape(-1,1)
y = np.array([4,3,2,1])
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
model = LinearRegression()
model.fit(x,y)
# y_prediction = model.predict(x)
# mse = mean_squared_error(y,y_prediction)
# mse
model.coef_

array([-1.])

In [ ]:
x1 = np.array([-3.5,2.1,-4.3,1.7,0.1]).reshape(-1,1)
x2 = np.array([1.9, -3.3,5.1,2.2,-0.1]).reshape(-1,1)
y = np.array([0.21,0.01,0.97,0.98,0.45]).reshape(-1,1)
X = np.hstack([x1,x2])
from sklearn.linear_model import LinearRegression
model = LinearRegression(fit_intercept= False)
model.fit(X,y)
print(model.coef_)

[[0.12844232 0.25365734]]


In [ ]:
y_pred = model.predict(X)
from sklearn.metrics import mean_squared_error
MSE_in =  mean_squared_error(y, y_pred)
print("MSE in inbuilt function:", MSE_in)

#manuel way
MSE = np.sum((y- y_pred)**2) / len(x)
print("MSE in manual way:", MSE)

MSE in inbuilt function: 0.13450476723079818
MSE in manual way: 0.16813095903849773


In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression(fit_intercept= False)
model.fit(X,y)
print(model.coef_)

[[0.12844232 0.25365734]]


In [3]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [14]:
x = np.array([10,9,2,15,10,16,11,16]).reshape(-1,1)
y = np.array([95,80,10,45,45,98,38,93])
model= LinearRegression(fit_intercept= True)
model.fit(x,y)
X_new = np.array([[20]])
model.predict(X_new)

array([102.59280458])